language: node_js
nvm:


matrix:
  include:
  - node_js: "6"
    script: nvm install 12 && npm run compile && nvm use 6 && npm run test-with-temp-cloud
  - node_js: "8"
    script: npm run test-with-temp-cloud
  - node_js: "10"
    script: npm run test-with-temp-cloud
  - node_js: "12"
    script: npm run test-with-temp-cloud
  - node_js: "14"
    script: npm run test-with-temp-cloud
